### ISSUE TITLE
Language from latex_template

### ISSUE THREAD

**Issue by PeterBlacken** [KarlWithK/dotfiles#1]
Hi! 
First of all i would like to thank you for your video about your latex template, since then I've been using your templates for my class notes and i feel pretty comfortable with them, but, i would like to do some changes, specific the language of somethings. 
I am in a university in Latin America and everyone speaks spanish  so i would like to change things like "contents" to "contentions" , or the colorboxes from "definitions" to "definiciones". 

My first approached to this problem was to "ctrl +F" to the word in the .tex files and start changing the words but it didn't end well because i'm new in latex. 

Any help will be well received!
Thx

**Comment by makarbaderko** [comment]
Hey, so what's your exact problem with ctrl + f ing?

**Comment by FahimAnayet** [comment]
Open `preamble.tex` file and change line no. 600. `\newcommand{\dfn}[2]{\begin{Definition}[colbacktitle=red!75!black]{#1}{}#2\end{Definition}} `

**Comment by SeniorMars** [comment]
@FahimAnayet is spot on!
