### ISSUE TITLE
Dark mode pdf

### ISSUE THREAD

**Issue by 2dope4writingcode** [KarlWithK/dotfiles#3]
Hi, I just started configuring my latex setup and I would like to have a dark mode preview like yours when I’m working at some notes.
How can I do that? Rn I have your template and preamble config, but my pdf viewer (Skim) makes the overall preview light and not dark. Thank you.

**Comment by JxJxxJxJ** [comment]
He uses _zathura_ to view PDFs, it has an option to customize its theme like _vim_, you do it in `~/.zathurarc`

**Comment by SeniorMars** [comment]
Yep! You can find my zathurarc at `.config/zathura/zathurarc`
